# Site settings

title: Allen Adell, Inc - National Healthcare Executive Search Firm # Title of your site
resume-email: resume@allenadell.com
info-email: info@allenadell.com
vcard-url: 
phone: 1 (813) 920-8900
business: Allen Adell Executive Search & Consulting
streetnum: 7853
streetname: Gunn Highway
suitenum: '#260'
city: Tampa
state: FL
zip: 33626-1611
country: United States


description: > # this means to ignore newlines until "baseurl:"
  Allen Adell is a retained executive search and human capital consulting firm whose 
  clients are primarily Healthcare providers, including companies that provide contract 
  managed and outsourced services to both the acute and post-acute healthcare marketplaces. 
  Our functional areas of specialization include C-suite, sales, business development, 
  marketing, financial, clinical and professional services. We have successfully completed 
  hundreds of searches throughout the United States.
baseurl: "/AllenAdell/" # the subpath of your site, e.g. /blog/
url: "https://massugugo.github.io" # the base hostname & protocol for your site

google-analytics-code: # google analytics tracking code
linkedin-name: charleshaines # linked in name

# Build settings
markdown: kramdown